title: RedSoil Modding Docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: dark

url: https://dioxazinestudios.github.io/redsoil/modding/
